### ISSUE TITLE
Can only concatenate str (not "NoneType") to str Error on a world

### ISSUE THREAD

**Issue by Zamrod** [jegasus/world-manager#9]
I attempted to use this on one of my worlds and it errors out with:

Traceback (most recent call last):
  File "C:\world-manager-0.0.2\jwm_cli.py", line 61, in <module>
    my_world_refs = jwm.one_liner_compress_world(
  File "C:\world-manager-0.0.2\jegasus_world_manager.py", line 1748, in one_liner_compress_world
    my_world_refs.fix_incorrect_file_extensions()
  File "C:\world-manager-0.0.2\jegasus_world_manager.py", line 941, in fix_incorrect_file_extensions
    new_img_path_for_ref = find_filename_that_doesnt_exist_yet(new_img_file_path_before_extension,
  File "C:\world-manager-0.0.2\jegasus_world_manager.py", line 1686, in find_filename_that_doesnt_exist_yet
    current_filename = file_path_before_extension + '.' + extension
TypeError: can only concatenate str (not "NoneType") to str

**Comment by Zamrod** [comment]
This appears to happen when temp_ref.img_encoding gets set to None

**Comment by jegasus** [comment]
Thanks for the report! I'll try to look into this within the next couple of weeks! 
I might get in touch with you over discord for some questions.
